# Generated by Django 4.1.7 on 2023-03-09 05:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=150)),
                ("category_img", models.ImageField(null=True, upload_to="categories/")),
            ],
            options={
                "verbose_name_plural": "4.Categories",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contry_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Districts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district_name", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "2.districts",
            },
        ),
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Mandal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mandal_name", models.CharField(max_length=200)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superior.districts",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3.Mandal",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("sub_category", models.CharField(max_length=200)),
                ("video", models.URLField(default="")),
                ("likes_count", models.IntegerField(default=0)),
                ("share_count", models.IntegerField(default=0)),
                ("spam_count", models.IntegerField(default=0)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
                ("status", models.CharField(max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superior.categories",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superior.country",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superior.districts",
                    ),
                ),
                (
                    "mandal",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superior.mandal",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "2.News",
            },
        ),
        migrations.CreateModel(
            name="Reporters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(default="", max_length=100)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "3.Reporters",
            },
        ),
        migrations.CreateModel(
            name="States",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_name", models.CharField(max_length=250)),
                (
                    "state_representing_image",
                    models.ImageField(null=True, upload_to="states/"),
                ),
            ],
            options={
                "verbose_name_plural": "1.States",
            },
        ),
        migrations.CreateModel(
            name="SubCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_category", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name_plural": "5.Sub Categories",
            },
        ),
        migrations.CreateModel(
            name="SuperAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "0.Super Admin",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.CharField(default="", max_length=100)),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.UUID("d382747e-ed24-46fe-9399-7ec66862e745"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=100)),
                ("otp", models.CharField(default="00000", max_length=10)),
                ("email", models.EmailField(default="", max_length=200)),
                (
                    "profile_picture",
                    models.ImageField(default="", upload_to="user_profiles/"),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superior.districts",
                    ),
                ),
                (
                    "mandal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superior.mandal",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="superior.states",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Polls",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(max_length=200)),
                ("option_1", models.CharField(max_length=200)),
                ("option_2", models.CharField(max_length=200)),
                ("option_3", models.CharField(default="", max_length=200)),
                ("option_4", models.CharField(default="", max_length=200)),
                ("option_1_count", models.IntegerField(default=0)),
                ("option_2_count", models.IntegerField(default=0)),
                ("option_3_count", models.IntegerField(default=0)),
                ("option_4_count", models.IntegerField(default=0)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
                ("status", models.CharField(default="published", max_length=200)),
                (
                    "responded_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="superior.users"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "6.Polls",
            },
        ),
        migrations.CreateModel(
            name="NewsImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(null=True, upload_to="news_imgs/")),
                (
                    "news_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_images",
                        to="superior.news",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=500)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_updated", models.DateField(auto_now=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
                (
                    "news_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="superior.news"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="superior.users"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="news",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="superior.states",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="superior.users"
            ),
        ),
        migrations.CreateModel(
            name="JobPostings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("jobSubCategory", models.CharField(max_length=200)),
                ("no_of_openings", models.CharField(max_length=200)),
                ("jobType", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("interested_in_hiring_from", models.CharField(max_length=200)),
                ("min_salary", models.IntegerField()),
                ("max_salary", models.IntegerField()),
                ("jobHours", models.CharField(max_length=200)),
                ("timings_shift", models.CharField(max_length=200)),
                ("company_name", models.CharField(max_length=200)),
                ("your_role_in_company", models.CharField(max_length=200)),
                ("manage_candidate_through", models.CharField(max_length=200)),
                ("phoneNumber", models.CharField(max_length=200)),
                ("whatsappNumber", models.CharField(max_length=200)),
                (
                    "company_logo",
                    models.ImageField(null=True, upload_to="job_post_company_logo/"),
                ),
                ("years_of_experience", models.CharField(max_length=200)),
                ("graduation", models.CharField(max_length=200)),
                ("Preferred_gender", models.CharField(max_length=200)),
                ("Fees_required", models.BooleanField(default=False)),
                ("Fee_amount", models.CharField(max_length=200, null=True)),
                ("fee_reasons", models.CharField(max_length=250)),
                ("Fee_before_getting_job", models.BooleanField(default=True)),
                ("additiona_info", models.TextField()),
                ("tac", models.BooleanField(default=False)),
                ("Job_poster", models.ImageField(null=True, upload_to="job_poster/")),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
                ("status", models.CharField(default="Under Review", max_length=200)),
                (
                    "JobCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobCategory",
                        to="superior.jobcategory",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="district",
                        to="superior.districts",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state",
                        to="superior.states",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="superior.users"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="districts",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="superior.states"
            ),
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("image", models.ImageField(null=True, upload_to="advertisements/")),
                ("link", models.URLField(blank=True, null=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("updated_time", models.TimeField(auto_now=True)),
                ("status", models.CharField(default="Under Review", max_length=200)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="superior.users"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "9.Advertisements",
            },
        ),
    ]
