# Generated by Django 4.1.7 on 2023-03-09 06:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("superior", "0002_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="status",
            field=models.CharField(default="Under Review", max_length=200),
        ),
        migrations.AlterField(
            model_name="news",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="superior.users",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("2eac6e67-0332-41f2-8875-beed0318004b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
