# Generated by Django 4.1.7 on 2023-03-09 06:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("superior", "0003_alter_news_status_alter_news_user_id_alter_users_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="polls",
            name="responded_user_id",
        ),
        migrations.AddField(
            model_name="advertisement",
            name="by_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobpostings",
            name="by_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="news",
            name="by_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="superior.users",
            ),
        ),
        migrations.AlterField(
            model_name="jobpostings",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="superior.users",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("d7b5cb4b-6c73-4eb5-a0c9-abc11815fbb7"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
