# Generated by Django 4.1.7 on 2023-03-09 07:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("superior", "0004_remove_polls_responded_user_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Epaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paper_name", models.CharField(max_length=500)),
                ("paper_file", models.FileField(upload_to="epaper/")),
                ("created_date", models.DateField(auto_now_add=True)),
                ("created_time", models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("365b2ca6-3da0-4953-b793-2eba62917ed7"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
