# Generated by Django 4.1.7 on 2023-03-10 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("superior", "0006_alter_jobpostings_whatsappnumber_alter_users_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpostings",
            name="fee_reasons",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="uid",
            field=models.UUIDField(
                default=uuid.UUID("80e8a6b2-77a6-4d83-86f5-f81d1c795bf0"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
